"""Add task name to job swaps

Revision ID: 764af4f641c7
Revises: 30e74c5564b3
Create Date: 2026-08-19 16:47:32.280538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764af4f641c7'
down_revision = '30e74c5564b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_swaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_swaps', schema=None) as batch_op:
        batch_op.drop_column('task_name')

    # ### end Alembic commands ###
